package com.jyt.dao;

import com.jyt.dataobject.FileDo;
import com.jyt.dataobject.FileDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    long countByExample(FileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int deleteByExample(FileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int deleteByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int insert(FileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int insertSelective(FileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    List<FileDo> selectByExample(FileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    FileDo selectByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") FileDo record, @Param("example") FileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int updateByExample(@Param("record") FileDo record, @Param("example") FileDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int updateByPrimaryKeySelective(FileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int updateByPrimaryKey(FileDo record);
}