package com.jyt.dao;

import com.jyt.dataobject.FileDo;

public interface FileDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int deleteByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int insert(FileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int insertSelective(FileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    FileDo selectByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int updateByPrimaryKeySelective(FileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int updateByPrimaryKey(FileDo record);
}