package com.jyt.dao;

import com.jyt.dataobject.ModelDo;
import com.jyt.dataobject.ModelDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModelDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    long countByExample(ModelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int deleteByExample(ModelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int deleteByPrimaryKey(Integer modelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int insert(ModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int insertSelective(ModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    List<ModelDo> selectByExample(ModelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    ModelDo selectByPrimaryKey(Integer modelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") ModelDo record, @Param("example") ModelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int updateByExample(@Param("record") ModelDo record, @Param("example") ModelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int updateByPrimaryKeySelective(ModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    int updateByPrimaryKey(ModelDo record);
}