package com.jyt.dao;

import com.jyt.dataobject.ModelDo;

public interface ModelDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int deleteByPrimaryKey(Integer modelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int insert(ModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int insertSelective(ModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    ModelDo selectByPrimaryKey(Integer modelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int updateByPrimaryKeySelective(ModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 11:27:39 CST 2019
     */
    int updateByPrimaryKey(ModelDo record);
}