package com.jyt.dataobject;

import java.util.Date;

public class FileDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.fileid
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    private Integer fileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.time
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.olddocx
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    private String olddocx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.label
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.featuretxt
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    private String featuretxt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.newdocx
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    private String newdocx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.fileid
     *
     * @return the value of file.fileid
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.fileid
     *
     * @param fileid the value for file.fileid
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.time
     *
     * @return the value of file.time
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.time
     *
     * @param time the value for file.time
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.olddocx
     *
     * @return the value of file.olddocx
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public String getOlddocx() {
        return olddocx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.olddocx
     *
     * @param olddocx the value for file.olddocx
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setOlddocx(String olddocx) {
        this.olddocx = olddocx == null ? null : olddocx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.label
     *
     * @return the value of file.label
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.label
     *
     * @param label the value for file.label
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.featuretxt
     *
     * @return the value of file.featuretxt
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public String getFeaturetxt() {
        return featuretxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.featuretxt
     *
     * @param featuretxt the value for file.featuretxt
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setFeaturetxt(String featuretxt) {
        this.featuretxt = featuretxt == null ? null : featuretxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.newdocx
     *
     * @return the value of file.newdocx
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public String getNewdocx() {
        return newdocx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.newdocx
     *
     * @param newdocx the value for file.newdocx
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setNewdocx(String newdocx) {
        this.newdocx = newdocx == null ? null : newdocx.trim();
    }
}