package com.jyt.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileDoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public FileDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFileidIsNull() {
            addCriterion("fileid is null");
            return (Criteria) this;
        }

        public Criteria andFileidIsNotNull() {
            addCriterion("fileid is not null");
            return (Criteria) this;
        }

        public Criteria andFileidEqualTo(Integer value) {
            addCriterion("fileid =", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotEqualTo(Integer value) {
            addCriterion("fileid <>", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidGreaterThan(Integer value) {
            addCriterion("fileid >", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidGreaterThanOrEqualTo(Integer value) {
            addCriterion("fileid >=", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidLessThan(Integer value) {
            addCriterion("fileid <", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidLessThanOrEqualTo(Integer value) {
            addCriterion("fileid <=", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidIn(List<Integer> values) {
            addCriterion("fileid in", values, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotIn(List<Integer> values) {
            addCriterion("fileid not in", values, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidBetween(Integer value1, Integer value2) {
            addCriterion("fileid between", value1, value2, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotBetween(Integer value1, Integer value2) {
            addCriterion("fileid not between", value1, value2, "fileid");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andOlddocxIsNull() {
            addCriterion("olddocx is null");
            return (Criteria) this;
        }

        public Criteria andOlddocxIsNotNull() {
            addCriterion("olddocx is not null");
            return (Criteria) this;
        }

        public Criteria andOlddocxEqualTo(String value) {
            addCriterion("olddocx =", value, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxNotEqualTo(String value) {
            addCriterion("olddocx <>", value, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxGreaterThan(String value) {
            addCriterion("olddocx >", value, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxGreaterThanOrEqualTo(String value) {
            addCriterion("olddocx >=", value, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxLessThan(String value) {
            addCriterion("olddocx <", value, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxLessThanOrEqualTo(String value) {
            addCriterion("olddocx <=", value, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxLike(String value) {
            addCriterion("olddocx like", value, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxNotLike(String value) {
            addCriterion("olddocx not like", value, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxIn(List<String> values) {
            addCriterion("olddocx in", values, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxNotIn(List<String> values) {
            addCriterion("olddocx not in", values, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxBetween(String value1, String value2) {
            addCriterion("olddocx between", value1, value2, "olddocx");
            return (Criteria) this;
        }

        public Criteria andOlddocxNotBetween(String value1, String value2) {
            addCriterion("olddocx not between", value1, value2, "olddocx");
            return (Criteria) this;
        }

        public Criteria andLabelIsNull() {
            addCriterion("label is null");
            return (Criteria) this;
        }

        public Criteria andLabelIsNotNull() {
            addCriterion("label is not null");
            return (Criteria) this;
        }

        public Criteria andLabelEqualTo(String value) {
            addCriterion("label =", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotEqualTo(String value) {
            addCriterion("label <>", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThan(String value) {
            addCriterion("label >", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThanOrEqualTo(String value) {
            addCriterion("label >=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThan(String value) {
            addCriterion("label <", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThanOrEqualTo(String value) {
            addCriterion("label <=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLike(String value) {
            addCriterion("label like", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotLike(String value) {
            addCriterion("label not like", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelIn(List<String> values) {
            addCriterion("label in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotIn(List<String> values) {
            addCriterion("label not in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelBetween(String value1, String value2) {
            addCriterion("label between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotBetween(String value1, String value2) {
            addCriterion("label not between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtIsNull() {
            addCriterion("featuretxt is null");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtIsNotNull() {
            addCriterion("featuretxt is not null");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtEqualTo(String value) {
            addCriterion("featuretxt =", value, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtNotEqualTo(String value) {
            addCriterion("featuretxt <>", value, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtGreaterThan(String value) {
            addCriterion("featuretxt >", value, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtGreaterThanOrEqualTo(String value) {
            addCriterion("featuretxt >=", value, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtLessThan(String value) {
            addCriterion("featuretxt <", value, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtLessThanOrEqualTo(String value) {
            addCriterion("featuretxt <=", value, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtLike(String value) {
            addCriterion("featuretxt like", value, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtNotLike(String value) {
            addCriterion("featuretxt not like", value, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtIn(List<String> values) {
            addCriterion("featuretxt in", values, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtNotIn(List<String> values) {
            addCriterion("featuretxt not in", values, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtBetween(String value1, String value2) {
            addCriterion("featuretxt between", value1, value2, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andFeaturetxtNotBetween(String value1, String value2) {
            addCriterion("featuretxt not between", value1, value2, "featuretxt");
            return (Criteria) this;
        }

        public Criteria andNewdocxIsNull() {
            addCriterion("newdocx is null");
            return (Criteria) this;
        }

        public Criteria andNewdocxIsNotNull() {
            addCriterion("newdocx is not null");
            return (Criteria) this;
        }

        public Criteria andNewdocxEqualTo(String value) {
            addCriterion("newdocx =", value, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxNotEqualTo(String value) {
            addCriterion("newdocx <>", value, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxGreaterThan(String value) {
            addCriterion("newdocx >", value, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxGreaterThanOrEqualTo(String value) {
            addCriterion("newdocx >=", value, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxLessThan(String value) {
            addCriterion("newdocx <", value, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxLessThanOrEqualTo(String value) {
            addCriterion("newdocx <=", value, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxLike(String value) {
            addCriterion("newdocx like", value, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxNotLike(String value) {
            addCriterion("newdocx not like", value, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxIn(List<String> values) {
            addCriterion("newdocx in", values, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxNotIn(List<String> values) {
            addCriterion("newdocx not in", values, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxBetween(String value1, String value2) {
            addCriterion("newdocx between", value1, value2, "newdocx");
            return (Criteria) this;
        }

        public Criteria andNewdocxNotBetween(String value1, String value2) {
            addCriterion("newdocx not between", value1, value2, "newdocx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 05 10:44:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}