package com.jyt.dataobject;

import java.util.ArrayList;
import java.util.List;

public class ModelDoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public ModelDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModelidIsNull() {
            addCriterion("modelid is null");
            return (Criteria) this;
        }

        public Criteria andModelidIsNotNull() {
            addCriterion("modelid is not null");
            return (Criteria) this;
        }

        public Criteria andModelidEqualTo(Integer value) {
            addCriterion("modelid =", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidNotEqualTo(Integer value) {
            addCriterion("modelid <>", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidGreaterThan(Integer value) {
            addCriterion("modelid >", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidGreaterThanOrEqualTo(Integer value) {
            addCriterion("modelid >=", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidLessThan(Integer value) {
            addCriterion("modelid <", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidLessThanOrEqualTo(Integer value) {
            addCriterion("modelid <=", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidIn(List<Integer> values) {
            addCriterion("modelid in", values, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidNotIn(List<Integer> values) {
            addCriterion("modelid not in", values, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidBetween(Integer value1, Integer value2) {
            addCriterion("modelid between", value1, value2, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidNotBetween(Integer value1, Integer value2) {
            addCriterion("modelid not between", value1, value2, "modelid");
            return (Criteria) this;
        }

        public Criteria andLabelIsNull() {
            addCriterion("label is null");
            return (Criteria) this;
        }

        public Criteria andLabelIsNotNull() {
            addCriterion("label is not null");
            return (Criteria) this;
        }

        public Criteria andLabelEqualTo(String value) {
            addCriterion("label =", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotEqualTo(String value) {
            addCriterion("label <>", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThan(String value) {
            addCriterion("label >", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThanOrEqualTo(String value) {
            addCriterion("label >=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThan(String value) {
            addCriterion("label <", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThanOrEqualTo(String value) {
            addCriterion("label <=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLike(String value) {
            addCriterion("label like", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotLike(String value) {
            addCriterion("label not like", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelIn(List<String> values) {
            addCriterion("label in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotIn(List<String> values) {
            addCriterion("label not in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelBetween(String value1, String value2) {
            addCriterion("label between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotBetween(String value1, String value2) {
            addCriterion("label not between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andModelcolIsNull() {
            addCriterion("modelcol is null");
            return (Criteria) this;
        }

        public Criteria andModelcolIsNotNull() {
            addCriterion("modelcol is not null");
            return (Criteria) this;
        }

        public Criteria andModelcolEqualTo(String value) {
            addCriterion("modelcol =", value, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolNotEqualTo(String value) {
            addCriterion("modelcol <>", value, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolGreaterThan(String value) {
            addCriterion("modelcol >", value, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolGreaterThanOrEqualTo(String value) {
            addCriterion("modelcol >=", value, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolLessThan(String value) {
            addCriterion("modelcol <", value, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolLessThanOrEqualTo(String value) {
            addCriterion("modelcol <=", value, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolLike(String value) {
            addCriterion("modelcol like", value, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolNotLike(String value) {
            addCriterion("modelcol not like", value, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolIn(List<String> values) {
            addCriterion("modelcol in", values, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolNotIn(List<String> values) {
            addCriterion("modelcol not in", values, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolBetween(String value1, String value2) {
            addCriterion("modelcol between", value1, value2, "modelcol");
            return (Criteria) this;
        }

        public Criteria andModelcolNotBetween(String value1, String value2) {
            addCriterion("modelcol not between", value1, value2, "modelcol");
            return (Criteria) this;
        }

        public Criteria andRolecollectionIsNull() {
            addCriterion("rolecollection is null");
            return (Criteria) this;
        }

        public Criteria andRolecollectionIsNotNull() {
            addCriterion("rolecollection is not null");
            return (Criteria) this;
        }

        public Criteria andRolecollectionEqualTo(String value) {
            addCriterion("rolecollection =", value, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionNotEqualTo(String value) {
            addCriterion("rolecollection <>", value, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionGreaterThan(String value) {
            addCriterion("rolecollection >", value, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionGreaterThanOrEqualTo(String value) {
            addCriterion("rolecollection >=", value, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionLessThan(String value) {
            addCriterion("rolecollection <", value, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionLessThanOrEqualTo(String value) {
            addCriterion("rolecollection <=", value, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionLike(String value) {
            addCriterion("rolecollection like", value, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionNotLike(String value) {
            addCriterion("rolecollection not like", value, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionIn(List<String> values) {
            addCriterion("rolecollection in", values, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionNotIn(List<String> values) {
            addCriterion("rolecollection not in", values, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionBetween(String value1, String value2) {
            addCriterion("rolecollection between", value1, value2, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andRolecollectionNotBetween(String value1, String value2) {
            addCriterion("rolecollection not between", value1, value2, "rolecollection");
            return (Criteria) this;
        }

        public Criteria andTraindataIsNull() {
            addCriterion("traindata is null");
            return (Criteria) this;
        }

        public Criteria andTraindataIsNotNull() {
            addCriterion("traindata is not null");
            return (Criteria) this;
        }

        public Criteria andTraindataEqualTo(String value) {
            addCriterion("traindata =", value, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataNotEqualTo(String value) {
            addCriterion("traindata <>", value, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataGreaterThan(String value) {
            addCriterion("traindata >", value, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataGreaterThanOrEqualTo(String value) {
            addCriterion("traindata >=", value, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataLessThan(String value) {
            addCriterion("traindata <", value, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataLessThanOrEqualTo(String value) {
            addCriterion("traindata <=", value, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataLike(String value) {
            addCriterion("traindata like", value, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataNotLike(String value) {
            addCriterion("traindata not like", value, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataIn(List<String> values) {
            addCriterion("traindata in", values, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataNotIn(List<String> values) {
            addCriterion("traindata not in", values, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataBetween(String value1, String value2) {
            addCriterion("traindata between", value1, value2, "traindata");
            return (Criteria) this;
        }

        public Criteria andTraindataNotBetween(String value1, String value2) {
            addCriterion("traindata not between", value1, value2, "traindata");
            return (Criteria) this;
        }

        public Criteria andExecodeIsNull() {
            addCriterion("execode is null");
            return (Criteria) this;
        }

        public Criteria andExecodeIsNotNull() {
            addCriterion("execode is not null");
            return (Criteria) this;
        }

        public Criteria andExecodeEqualTo(String value) {
            addCriterion("execode =", value, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeNotEqualTo(String value) {
            addCriterion("execode <>", value, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeGreaterThan(String value) {
            addCriterion("execode >", value, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeGreaterThanOrEqualTo(String value) {
            addCriterion("execode >=", value, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeLessThan(String value) {
            addCriterion("execode <", value, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeLessThanOrEqualTo(String value) {
            addCriterion("execode <=", value, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeLike(String value) {
            addCriterion("execode like", value, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeNotLike(String value) {
            addCriterion("execode not like", value, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeIn(List<String> values) {
            addCriterion("execode in", values, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeNotIn(List<String> values) {
            addCriterion("execode not in", values, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeBetween(String value1, String value2) {
            addCriterion("execode between", value1, value2, "execode");
            return (Criteria) this;
        }

        public Criteria andExecodeNotBetween(String value1, String value2) {
            addCriterion("execode not between", value1, value2, "execode");
            return (Criteria) this;
        }

        public Criteria andHdf5IsNull() {
            addCriterion("hdf5 is null");
            return (Criteria) this;
        }

        public Criteria andHdf5IsNotNull() {
            addCriterion("hdf5 is not null");
            return (Criteria) this;
        }

        public Criteria andHdf5EqualTo(String value) {
            addCriterion("hdf5 =", value, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5NotEqualTo(String value) {
            addCriterion("hdf5 <>", value, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5GreaterThan(String value) {
            addCriterion("hdf5 >", value, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5GreaterThanOrEqualTo(String value) {
            addCriterion("hdf5 >=", value, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5LessThan(String value) {
            addCriterion("hdf5 <", value, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5LessThanOrEqualTo(String value) {
            addCriterion("hdf5 <=", value, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5Like(String value) {
            addCriterion("hdf5 like", value, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5NotLike(String value) {
            addCriterion("hdf5 not like", value, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5In(List<String> values) {
            addCriterion("hdf5 in", values, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5NotIn(List<String> values) {
            addCriterion("hdf5 not in", values, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5Between(String value1, String value2) {
            addCriterion("hdf5 between", value1, value2, "hdf5");
            return (Criteria) this;
        }

        public Criteria andHdf5NotBetween(String value1, String value2) {
            addCriterion("hdf5 not between", value1, value2, "hdf5");
            return (Criteria) this;
        }

        public Criteria andYmlIsNull() {
            addCriterion("yml is null");
            return (Criteria) this;
        }

        public Criteria andYmlIsNotNull() {
            addCriterion("yml is not null");
            return (Criteria) this;
        }

        public Criteria andYmlEqualTo(String value) {
            addCriterion("yml =", value, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlNotEqualTo(String value) {
            addCriterion("yml <>", value, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlGreaterThan(String value) {
            addCriterion("yml >", value, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlGreaterThanOrEqualTo(String value) {
            addCriterion("yml >=", value, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlLessThan(String value) {
            addCriterion("yml <", value, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlLessThanOrEqualTo(String value) {
            addCriterion("yml <=", value, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlLike(String value) {
            addCriterion("yml like", value, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlNotLike(String value) {
            addCriterion("yml not like", value, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlIn(List<String> values) {
            addCriterion("yml in", values, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlNotIn(List<String> values) {
            addCriterion("yml not in", values, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlBetween(String value1, String value2) {
            addCriterion("yml between", value1, value2, "yml");
            return (Criteria) this;
        }

        public Criteria andYmlNotBetween(String value1, String value2) {
            addCriterion("yml not between", value1, value2, "yml");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table model
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 05 10:44:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table model
     *
     * @mbg.generated Thu Dec 05 10:44:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}